name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

env:
  NODE_VERSION: 16.x

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/checkout@v3
      - run: |
          npm ci
          npm run typecheck
          npm run lint
          npm run build

      - name: Update documentation
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: github.event_name != 'pull_request'
        with:
          branch: gh-pages
          folder: docs
